const art = name => `./assets/choices/${name}.svg`;

const choice = (label, emoji, illustration, consequence) => ({ label, emoji, illustration: art(illustration), consequence });

const stories = [
  {
    id: 'mila-oeuf-orage', title: 'Mila et l’Œuf de l’Orage', coverEmoji: '🥚',
    coverImage: './assets/stories/mila-oeuf-orage/cover.jpg', ageRange: '5–9 ans', ageBand: '5-9', heroVoice: 'female', durationMinutes: 8,
    intro: 'Un œuf de dinosaure vient de tomber du ciel. Mila n’a que huit minutes avant que l’orage ne retrouve sa trace.',
    bible: { premise: 'Mila protège un œuf de dinosaure tombé d’un nuage préhistorique.', theme: 'Le courage attentif', values: ['entraide', 'curiosité', 'respect du vivant'], heroGoal: 'Ramener l’œuf à sa famille avant le grand éclair.', stakes: 'L’œuf éclora loin des siens si le passage du ciel se referme.', recurringObjects: ['l’œuf turquoise', 'la boussole-plume', 'le tonnerre qui fait boum-boum'] },
    transitions: [
      'Au loin, le tonnerre répond : boum… boum. Pas méchant, mais pressé. Sur la coquille, une ligne de lumière dessine une flèche. Mila remet la boussole-plume dans sa poche et avance : le prochain indice les attend déjà.',
      'L’œuf devient tiède contre son manteau. À l’intérieur, quelque chose gratte trois fois : cric, cric, cric. Mila comprend qu’elle n’est plus seule à décider. Elle chuchote ce qu’elle va faire, et le petit être répond par un minuscule toc.',
      'Une rafale soulève les feuilles sans emporter Mila. La boussole-plume tourne puis s’immobilise vers les hauteurs. Il reste peu de temps avant le grand éclair, mais chaque bon choix a rendu leur chemin un peu plus clair.',
      'La vallée entière semble retenir son souffle. Mila aperçoit enfin le pont d’arc-en-ciel qui mène au nuage des dinosaures. Il clignote comme une veilleuse presque déchargée. Pour l’atteindre, il faudra encore comprendre ce que demande l’œuf.',
      'Derrière les nuages, une silhouette à trois cornes appelle doucement. La famille est proche. Mila sent le petit dinosaure pousser contre la coquille : il veut sortir, mais surtout il veut entendre une voix rassurante pour son dernier passage.'
    ],
    episodes: [
      { headline: 'L’œuf qui tombe du ciel', emoji: '⛈️', mood: 'wonder', pace: 'lively', scene: `Mila collectionne les bruits de pluie. Ploc sur les feuilles, flic-flac dans les flaques, frou-frou sous son capuchon jaune. Mais ce soir-là, un bruit nouveau traverse le jardin : fiiiiou… POUF ! Dans les capucines repose un œuf gros comme un ballon, turquoise, couvert de petites étoiles lumineuses. Une voix de tonnerre gronde au-dessus des nuages : « Objet perdu ! Retour avant le grand éclair ! » L’œuf tremble. Mila pose une main dessus et sent un cœur minuscule battre très vite. Près du trou dans les fleurs, elle découvre une plume aimantée qui tourne comme une boussole. Un chemin de traces rondes file vers le bois, tandis qu’un courant d’air doré monte droit vers le vieux moulin.`, question: 'Pour trouver d’où vient l’œuf, que fait Mila ?', choices: [choice('Suivre les traces du bois', '👣', 'suivre', `Mila s’accroupit pour ne perdre aucune empreinte. Les traces appartiennent à un bébé tricératops transparent comme une bulle. Il s’était échappé du nuage pour chercher l’œuf. Rassuré par la douceur de Mila, il lui confie que les dinosaures du ciel rejoignent leur vallée par le vieux moulin.`), choice('Monter vers le moulin', '🧭', 'explorer', `Mila suit le souffle doré jusqu’au moulin. Dans ses ailes immobiles est coincé un ruban de nuage couvert d’empreintes de tricératops. Quand elle approche l’œuf, les ailes grincent et désignent le bois : le gardien du passage s’y cache depuis le coup de tonnerre.`)] },
      { headline: 'Le gardien aux trois cornes', emoji: '🦕', mood: 'mystery', pace: 'normal', scene: `Sous les fougères, deux yeux brillent. Le bébé tricératops surgit et gonfle ses joues pour paraître terrible. Il n’est pas plus haut qu’un tabouret. « Je suis Toupik, gardien remplaçant du passage ! » annonce-t-il d’une voix qui couine. Il reconnaît l’œuf de sa petite sœur, puis baisse la tête : pendant l’orage, il a eu peur et la boussole-plume s’est cassée en deux. Une moitié est dans la poche de Mila ; l’autre pend au collier d’un grand corbeau sur une branche. Le corbeau ne vole rien : il adore seulement les objets qui chantent. Mila pourrait lui proposer un échange ou chercher à reproduire le chant de la plume.`, question: 'Comment récupérer l’autre moitié de la boussole ?', choices: [choice('Lui offrir un grelot', '🔔', 'partager', `Mila détache le petit grelot de sa fermeture éclair et le fait tinter. Le corbeau incline la tête, ravi, puis dépose la demi-plume dans sa paume. Toupik comprend qu’un échange respectueux vaut mieux qu’un ordre crié. Il promet de rendre un service à son tour.`), choice('Imiter le chant de la plume', '🎶', 'chanter', `Mila souffle entre ses mains : « fi-ou, fi-ou ». Toupik ajoute un « prout-prout » involontaire avec ses naseaux. Le corbeau éclate d’un croassement joyeux et accompagne leur drôle de musique ; son collier s’ouvre tout seul, libérant la demi-plume.`)] },
      { headline: 'La rivière qui monte', emoji: '🌊', mood: 'suspense', pace: 'lively', scene: `Les deux morceaux réunis, la boussole-plume pointe vers le moulin. Mais le ruisseau est devenu une large rivière brune. Sur une pierre, une famille de musaraignes attend, entourée d’eau. Toupik veut foncer : sa sœur est de l’autre côté. L’œuf, lui, pulse d’une lumière orange chaque fois que les petites bêtes appellent. Mila voit un tronc solide retenu par des lianes. Plus loin, de grandes feuilles creuses pourraient devenir des barques. Le tonnerre se rapproche : boum-BOUM. Il faut traverser, mais l’œuf semble refuser qu’on laisse les musaraignes derrière.`, question: 'Quelle traversée Mila prépare-t-elle ?', choices: [choice('Construire un pont de tronc', '🌉', 'inventer', `Mila et Toupik tirent ensemble sur les lianes. Le tronc se pose d’une rive à l’autre. Toupik traverse d’abord, pattes écartées, puis revient chercher les musaraignes une par une. Cette prudence prend un peu de temps, mais tous arrivent secs et fiers.`), choice('Faire des barques-feuilles', '🍃', 'aider', `Mila replie les bords des grandes feuilles et Toupik les pousse du museau. Les musaraignes embarquent avec l’œuf au centre, bien calé dans de la mousse. Le courant les fait tournoyer, puis les dépose juste devant le moulin dans un éclat de rire.`)] },
      { headline: 'Le moulin aux ailes endormies', emoji: '🌬️', mood: 'gentle_fear', pace: 'normal', scene: `Le moulin est noir et silencieux. Sa porte s’ouvre avec un long iiiiiik. À l’intérieur, un escalier monte entre des engrenages énormes. Le passage vers le ciel ne s’ouvrira que si les ailes recommencent à tourner. Toupik repère deux solutions : grimper pour décoincer le ruban de nuage, ou appeler toutes les petites bêtes sauvées afin qu’elles soufflent ensemble dans les pales du bas. Une lueur blanche fend une fenêtre. Mila a le ventre serré, mais elle se rappelle qu’avoir peur n’interdit pas d’agir. Elle serre l’œuf, qui répond toc-toc, comme pour l’encourager.`, question: 'Comment réveiller le moulin ?', choices: [choice('Grimper jusqu’au ruban', '🪢', 'courage', `Mila monte lentement, trois marches à la fois, puis s’arrête pour respirer. Toupik guide ses pieds depuis le sol. Elle atteint le ruban et défait le nœud sans tirer brusquement. Une rafale libérée emplit le moulin ; ses grandes ailes commencent à tourner.`), choice('Souffler tous ensemble', '💨', 'aider', `Mila appelle les musaraignes et le corbeau. Chacun inspire. « Un, deux, trois… FROUUU ! » Toupik souffle si fort qu’il recule sur les fesses. Le premier tour est minuscule, le deuxième plus grand, et bientôt les ailes brassent un vent couleur de miel.`)] },
      { headline: 'Le pont du grand éclair', emoji: '🌈', mood: 'triumph', pace: 'normal', final: true, scene: `Un escalier de lumière jaillit du moulin jusqu’au pont d’arc-en-ciel. De l’autre côté, la maman tricératops appelle son petit dans un grondement tendre. Mais le grand éclair gonfle le nuage au-dessus de Mila. La coquille craque : une petite corne apparaît. Toupik panique, le pont vacille et la boussole-plume indique trois signes : une note de musique, un cœur, et une étoile immobile. Mila comprend qu’il n’existe pas une seule bonne manière de rassurer le bébé. Il faut choisir celle que toute leur aventure lui a apprise, puis franchir ensemble les dernières couleurs du pont.`, question: 'Quel courage Mila partage-t-elle avec le bébé ?', choices: [choice('Chanter leur drôle de chanson', '🎵', 'chanter', `Mila reprend « fi-ou, fi-ou » et Toupik ajoute son fameux « prout-prout ». Le bébé cesse de pousser la coquille et écoute. Le pont vibre au même rythme ; ils traversent en chantant, juste avant que l’éclair illumine le ciel comme un feu d’artifice.`), choice('Lui raconter tous les gestes d’entraide', '💗', 'partager', `Mila raconte le corbeau, les musaraignes et tous ceux qui ont aidé. À chaque merci, une couleur du pont devient plus solide. Le bébé donne un petit coup confiant. Toute la troupe avance serrée, portée par les liens qu’elle a créés.`), choice('Respirer et avancer tout doucement', '⭐', 'attendre', `Mila pose la main sur la coquille. Ensemble, ils inspirent pendant trois couleurs et expirent pendant trois autres. Le vacarme paraît moins grand. Pas après pas, sans courir, ils atteignent la maman tricératops au moment où le ciel redevient bleu.`)] }
    ],
    endings: [
      { title: 'La chanson du ciel', emoji: '🎶', text: `La coquille s’ouvre dans les bras de sa maman. Une petite tricératops turquoise éternue une étincelle, puis réclame encore la chanson. Les dinosaures du nuage la reprennent tous, même les plus grands. Mila reçoit une plume neuve qui fredonne quand quelqu’un a besoin de courage. Depuis ce soir, les orages du jardin font parfois « boum, boum… prout-prout ». Et Mila sourit, car elle sait exactement qui chante là-haut.` },
      { title: 'Le pont des mercis', emoji: '💞', text: `Le bébé naît entouré de tous ceux que Mila a réunis. Sa maman le nomme Merci, parce que ce mot a réparé le passage. Le pont d’arc-en-ciel reste visible une minute de plus, juste assez pour que les musaraignes et le corbeau saluent les dinosaures. Mila rentre avec le grelot rendu et une certitude nouvelle : les plus grands voyages se construisent parfois avec de tout petits gestes.` },
      { title: 'La gardienne calme', emoji: '🌤️', text: `Le bébé sort de sa coquille au moment précis où Mila pose le pied dans la vallée des nuages. Il ne pleure pas : il respire avec elle. La maman tricératops confie à Mila le titre de Gardienne calme des passages pressés. Quand elle redescend, le grand éclair n’est plus qu’une fine étoile blanche. Dans sa poche, la boussole-plume pointe désormais vers les êtres qui ont besoin d’être rassurés.` }
    ]
  },
  {
    id: 'sacha-poste-oceans', title: 'Sacha et la Poste des Océans', coverEmoji: '💌',
    coverImage: './assets/stories/sacha-poste-oceans/cover.jpg', ageRange: '5–9 ans', ageBand: '5-9', heroVoice: 'male', durationMinutes: 8,
    intro: 'Une lettre lumineuse cherche son destinataire sous la mer. Sacha devient facteur des océans pour empêcher une ville de perdre ses couleurs.',
    bible: { premise: 'Sacha livre une lettre capable de rendre les couleurs à Coralline.', theme: 'Écouter avant de conclure', values: ['écoute', 'entraide', 'ingéniosité'], heroGoal: 'Identifier le vrai destinataire avant le coucher de la lune.', stakes: 'La cité sous-marine deviendra grise et silencieuse.', recurringObjects: ['la lettre lumineuse', 'le tampon-coquillage', 'la pieuvre Octavia'] },
    transitions: [
      'Le tampon-coquillage fait « plop » et imprime un nouvel indice sur l’enveloppe. Sacha le lit à la lumière des poissons-lanternes. La lettre frémit, impatiente, tandis qu’au loin une couleur disparaît d’une maison de Coralline.',
      'Octavia range l’indice dans l’une de ses huit poches. « Une poche par idée, c’est pratique ! » dit-elle. La lettre laisse échapper trois bulles dorées qui filent vers le quartier suivant. Sacha s’élance derrière elles.',
      'Le courant change et la cité perd encore un peu de bleu. Sacha se rappelle la règle des facteurs : une adresse ne se devine pas, elle s’observe. Il retourne l’enveloppe ; un dessin caché apparaît dans le papier mouillé.',
      'Toutes les pistes convergent vers la grande place. Le silence y est si épais qu’on entend les crabes marcher sur la pointe des pinces. Au centre attend une boîte aux lettres fermée par trois symboles.',
      'La lettre s’ouvre enfin, mais ses mots s’envolent en bulles avant qu’on puisse les lire. Sacha peut encore choisir comment partager le message : par la musique, par les images ou en réunissant toute la ville autour de lui.'
    ],
    episodes: [
      { headline: 'La bouteille qui appelle', emoji: '🌊', mood: 'wonder', pace: 'lively', scene: `Sur la plage, Sacha construit un port pour coquillages lorsqu’une bouteille remonte le sable à contre-vague. À l’intérieur brille une enveloppe marquée : « À celle ou celui qui garde toutes les couleurs. Cité de Coralline. Urgent avant le coucher de la lune. » Dès qu’il la touche, une bulle géante l’enveloppe. Plouf ! Sacha descend sous la mer sans être mouillé. Une pieuvre lavande, Octavia, l’attend avec une casquette de postière. Elle explique que trois habitants prétendent garder les couleurs : le peintre hippocampe, la baleine chanteuse et le vieux jardinier corail. La lettre ne s’ouvrira que devant le bon destinataire.`, question: 'Par quelle piste commencer ?', choices: [choice('Observer le timbre de près', '🔎', 'observer', `Sous sa loupe, Sacha découvre que le timbre n’est pas une fleur mais une minuscule partition en forme d’algue. Octavia pense aussitôt à la baleine chanteuse. Pourtant, au dos, un grain de pollen rouge rappelle aussi le jardin du vieux corail.`), choice('Demander aux poissons facteurs', '🐟', 'demander', `Les poissons facteurs ont vu l’enveloppe traverser un jardin rouge avant de suivre une mélodie. Ils ne sont pas d’accord sur l’ordre. Sacha dessine leurs témoignages plutôt que de choisir trop vite : deux pistes peuvent être vraies à la fois.`)] },
      { headline: 'Le marché aux mille bruits', emoji: '🐚', mood: 'joy', pace: 'lively', scene: `Pour rejoindre les suspects, Sacha et Octavia traversent le marché. Mais toutes les enseignes parlent en même temps : les moules vendent des chapeaux, les crevettes annoncent la météo et un crabe répète « par ici » dans huit directions. Au milieu du vacarme, la lettre émet un petit tintement régulier. Sacha distingue aussi un vendeur de cartes qui a aperçu une lueur dorée, et un banc de sardines qui connaît une chanson parlant de la gardienne des couleurs. Ils n’ont le temps d’interroger qu’un seul groupe avant que le courant emporte le marché.`, question: 'Qui Sacha écoute-t-il ?', choices: [choice('Le vendeur de cartes', '🗺️', 'demander', `Le vendeur déroule un plan transparent. La lueur venait de l’ancienne serre, reliée à la scène de concert par un tunnel oublié. Il prête à Sacha une craie d’eau qui peut tracer un chemin même au milieu d’un courant.`), choice('Les sardines chanteuses', '🎼', 'ecouter', `Les sardines chantent doucement, une seule à la fois. Leur refrain dit : « Elle garde le rouge avec ses branches, le bleu avec sa voix. » Sacha comprend que le destinataire pourrait ne pas être une personne, mais une équipe.`)] },
      { headline: 'La serre sans rouge', emoji: '🪸', mood: 'mystery', pace: 'normal', scene: `Dans l’ancienne serre, le vieux jardinier corail protège une dernière anémone rouge sous une cloche de verre. Il jure ne pas attendre de lettre. « Les couleurs ne m’appartiennent pas, je les fais pousser », précise-t-il. Soudain, des oursins roulent dans l’allée et menacent la fragile anémone. Sacha peut sécuriser la plante avec un cercle de coquilles, ou utiliser la craie d’eau pour guider les oursins vers une pente douce. Le jardinier promet ensuite de révéler ce qu’il sait sur l’enveloppe.`, question: 'Comment protéger l’anémone ?', choices: [choice('Former un rempart de coquilles', '🐚', 'aider', `Sacha empile les coquilles en demi-lune. Octavia utilise quatre bras pour construire et quatre autres pour ralentir les oursins. Le rempart tient. Reconnaissant, le jardinier donne un pétale rouge : posé sur la lettre, il fait apparaître le dessin d’une grande oreille.`), choice('Tracer une piste sûre', '〰️', 'inventer', `La craie dessine une route phosphorescente. Les oursins la suivent comme un petit train et terminent leur course dans un coussin d’algues. Le jardinier rit de soulagement puis révèle qu’une grande chanteuse venait autrefois écouter pousser les coraux.`)] },
      { headline: 'La baleine qui ne chante plus', emoji: '🐋', mood: 'sadness', pace: 'slow', scene: `La baleine Alba flotte derrière la scène de concert, silencieuse. Depuis que la ville perd ses couleurs, elle n’entend plus la note bleue qui guidait son chant. La lettre brille très fort près d’elle, mais reste fermée. Sacha remarque une corde d’algues coincée dans les tuyaux de l’orgue marin. Il pourrait la dégager tout de suite, ou demander d’abord à Alba d’écouter le battement de la lettre. Octavia murmure qu’une réparation soigne le problème, tandis qu’une écoute peut révéler sa cause. Les deux seront utiles ; il faut choisir par où commencer.`, question: 'Que fait Sacha en premier ?', choices: [choice('Libérer l’orgue marin', '🎹', 'aider', `Sacha plonge dans les tuyaux pendant qu’Octavia tient la corde. Un banc de petites crevettes pousse avec eux. L’orgue expire enfin une note grave et bleue. Alba retrouve sa voix, mais chante : « La lettre n’est pas seulement pour moi. »`), choice('Écouter le battement de la lettre', '💓', 'ecouter', `Alba pose l’enveloppe contre sa grande oreille. Entre deux battements, elle entend des voix mêlées : corail, poissons, vagues et enfants. « Ce message est pour la ville entière », souffle-t-elle. Sa certitude fait revenir une fine bande bleue sur la place.`)] },
      { headline: 'La boîte aux trois symboles', emoji: '📬', mood: 'triumph', pace: 'normal', final: true, scene: `Sur la grande place, Sacha place le pétale rouge, la note bleue et le tampon-coquillage sur la boîte. Elle s’ouvre : le destinataire était « Tous les habitants qui prennent soin les uns des autres ». La lettre contient une phrase, mais le courant la transforme aussitôt en centaines de bulles-mots. Certaines montent trop haut, d’autres se cachent sous les pavés. Les habitants se rassemblent, inquiets. Sacha sait désormais que le message ne doit pas appartenir à une seule voix. Il peut organiser une chanson, dessiner une fresque ou inviter chacun à récupérer puis offrir un mot à son voisin.`, question: 'Comment livrer la lettre à toute la ville ?', choices: [choice('Faire chanter les mots', '🎶', 'chanter', `Alba donne la note bleue, les sardines portent le refrain et même les crabes trouvent le rythme. Chaque bulle-mot éclate au bon moment pour former le message. Les façades se recolorent comme une vague de confettis.`), choice('Peindre une grande fresque', '🎨', 'inventer', `Sacha mélange le rouge du jardin, le bleu de la chanson et l’or de la lettre. Octavia peint avec huit pinceaux. La fresque montre chaque habitant en train d’aider un autre ; les couleurs jaillissent du mur et retournent dans toute la cité.`), choice('Partager les mots un par un', '🤝', 'partager', `Chaque habitant attrape une bulle, lit son mot et l’offre à quelqu’un : « écouter », « réparer », « rire », « attendre ». De nageoire en tentacule, la phrase entière circule. Les couleurs reviennent lentement, mais elles ne disparaîtront plus.`)] }
    ],
    endings: [
      { title: 'Le grand concert des couleurs', emoji: '🎵', text: `Le message disait : « Une ville garde ses couleurs quand toutes ses voix trouvent leur place. » Coralline nomme Sacha facteur-chef des refrains impossibles. Octavia lui tamponne la main d’une marque qui ne s’efface qu’à marée basse. De retour sur la plage, Sacha colle son oreille à un coquillage. Il entend Alba chanter, les sardines répondre et, tout au fond, un crabe annoncer fièrement : « Par ici… pour la prochaine aventure ! »` },
      { title: 'La fresque vivante', emoji: '🖼️', text: `La fresque reste sur la grande place et change chaque fois qu’un habitant accomplit un geste généreux. Sacha y apparaît avec son écharpe rouge, tenant la lettre devenue blanche. Avant son départ, le vieux jardinier lui offre une graine de corail qui peut pousser hors de l’eau. Dans son port de coquillages, elle devient une petite boîte aux lettres : désormais, Coralline saura où envoyer ses mystères.` },
      { title: 'Les mots voyageurs', emoji: '💌', text: `À force d’être partagés, les mots deviennent des poissons minuscules qui illuminent les rues. Chacun porte une couleur et une promesse. Sacha refuse une médaille : il préfère recevoir le premier sac officiel de la Poste des Océans, juste à sa taille. Le soir, une nouvelle enveloppe y apparaît. Elle n’est pas urgente. Elle dit simplement : « Merci d’avoir écouté jusqu’au bout. »` }
    ]
  },
  {
    id: 'aya-phare-reves', title: 'Aya et le Phare des Rêves', coverEmoji: '🔦',
    coverImage: './assets/stories/aya-phare-reves/cover.jpg', ageRange: '5–9 ans', ageBand: '5-9', heroVoice: 'female', durationMinutes: 20,
    intro: 'Cette nuit, le phare qui guide les rêves s’est éteint. Aya doit rallumer ses sept couleurs avant que les cauchemars ne perdent le chemin de la sortie.',
    bible: { premise: 'Aya répare un phare dont chaque couleur est liée à une émotion.', theme: 'Toutes les émotions peuvent guider', values: ['écoute de soi', 'empathie', 'courage'], heroGoal: 'Rallumer les sept couleurs du phare avant minuit.', stakes: 'Les rêves resteront bloqués et les cauchemars envahiront le village.', recurringObjects: ['le chat Ombre', 'la lanterne aux sept vitres', 'la clé en forme de lune', 'le refrain je peux écouter'] },
    transitions: [
      'Une vitre de la lanterne se rallume. Sa couleur dessine un chemin sur le sol, et Ombre le suit avec sa queue en point d’interrogation. Plus ils avancent, plus Aya comprend que le phare ne réclame pas des émotions parfaites : il veut qu’on les écoute vraiment.',
      'La clé-lune devient plus chaude dans la main d’Aya. Au-dessus d’eux, le faisceau du phare tente un tour puis s’éteint de nouveau. Dans le village endormi, une fenêtre s’agite sous un mauvais rêve. Il faut retrouver la couleur suivante.',
      'Ombre souffle : « Une émotion chassée revient souvent frapper plus fort. » Aya répète leur refrain : « Je peux écouter, je peux respirer, je peux choisir mon prochain pas. » Les murs du phare s’écartent et découvrent un escalier secret.',
      'La lanterne projette maintenant plusieurs couleurs à la fois. Elles ne se mélangent pas en gris : elles forment une aurore. Aya reprend courage. Minuit approche, mais le phare commence enfin à reconnaître sa gardienne.',
      'Un gong lointain annonce encore un peu de temps. Dans la salle suivante, les rêves perdus attendent sous forme de papillons. Certains tremblent, d’autres rient trop fort. Aya doit trouver ce que leur émotion essaie de protéger.',
      'Chaque papillon libéré rejoint le sommet. Ombre cesse de faire le malin et marche tout près d’Aya. La clé-lune porte désormais une minuscule empreinte de patte : même les guides ont parfois besoin d’être accompagnés.',
      'Les sept vitres sont presque complètes. Pourtant, une grande tache sans couleur bloque l’escalier. Elle porte la forme exacte de ce qu’Aya n’a jamais osé dire à voix haute. Le phare attend qu’elle choisisse une manière sûre de l’approcher.',
      'La tache se transforme en porte. Derrière, le vent des rêves souffle si fort que les marches deviennent des vagues. Aya distingue la salle de la lentille, tout en haut. Une dernière énigme sépare encore les émotions de leur lumière.',
      'Dans la lentille, toutes les couleurs tournent mais refusent de s’unir. Une voix demande : « Qui commande aux émotions ? » Aya sourit : personne ne commande tout à fait. On peut les accueillir, comprendre leur message, puis décider de ses gestes.',
      'Minuit sonne. Le phare s’allume une seconde puis révèle trois chemins pour guider les rêves : un faisceau vers le village, une constellation au-dessus de la mer, ou une ronde de lanternes portée par tous les rêveurs réveillés.'
    ],
    reflections: [
      `La barque s’attache seule au quai avec un nœud de lumière. Aya regarde le village minuscule derrière elle. Elle pourrait encore rentrer, pourtant elle pense aux enfants qui tournent dans leurs draps sans trouver la porte du matin. Elle nomme ce qu’elle ressent : un peu de peur, beaucoup de curiosité, et l’envie d’aider. Les trois peuvent voyager ensemble.`,
      `Avant de quitter la salle, Aya garde un ballon minuscule dans sa poche. Il ne crie pas ; il pulse simplement comme un soleil tranquille. Elle se rappelle une joie qu’elle n’avait racontée à personne : le jour où elle avait appris à faire du vélo. La garder avait été agréable, mais la partager maintenant réchauffe aussi Ombre.`,
      `Le rêve en armure essaie sa nouvelle phrase. Sa voix tremble d’abord, puis devient claire. La porte qu’il avait claquée se rouvre et un autre rêve vient l’écouter. Ils ne sont pas encore d’accord, mais ils peuvent parler sans se faire mal. Aya découvre qu’une colère bien comprise peut protéger une limite sans brûler tout le jardin.`,
      `La fillette de brume offre à Aya une fleur bleue qui ne fane pas quand on pleure. Elles parlent des souvenirs qui font sourire et piquer les yeux en même temps. Ombre recueille l’eau de pluie dans une tasse et la verse au pied d’un arbre. Ici, même les larmes ont un travail : elles aident quelque chose à pousser.`,
      `Dans un coin de la bibliothèque, Aya découvre un livre encore fermé. Son titre est « Peurs que je rencontrerai peut-être ». Elle décide de ne pas l’ouvrir ce soir. Se préparer ne veut pas dire tout imaginer à l’avance. Elle peut garder la veilleuse, connaître la sortie et demander une patte amie si une nouvelle histoire devient trop grande.`,
      `La fougère tend à Aya une graine toute simple. Elle ne ressemble ni à une étoile ni à un bijou, mais elle contient sa propre forme à venir. Aya la glisse dans la terre du phare. Peut-être deviendra-t-elle haute, peut-être large. Elle n’a pas besoin de ressembler à sa voisine pour mériter la lumière.`,
      `Ombre montre alors sous son pelage une petite tache rose semblable. Lui aussi s’était trompé autrefois en guidant un rêve vers la mauvaise porte. Il avait caché ce souvenir derrière des plaisanteries. Aya ne le juge pas. Ensemble, ils ajoutent à la lanterne une règle : ici, on peut réparer sans devoir disparaître.`,
      `Les papillons testent les marches à leur façon. L’un s’arrête, l’autre revient en arrière, un troisième demande à être porté. Aucun rythme n’est puni. Aya comprend qu’être souple ne signifie pas aimer tous les changements ; cela signifie garder assez d’attention pour trouver un appui quand le sol devient nouveau.`,
      `La lumière dorée descend jusque dans le carnet d’Aya et souligne les moments invisibles : celui où elle a attendu, celui où elle a changé d’avis, celui où elle a demandé à Ombre ce qu’il pensait. Le phare ne compte pas seulement les exploits. Il reconnaît les efforts silencieux qui ont permis aux autres couleurs d’apparaître.`,
      `Avant le geste final, Aya fait le tour de la lentille et vérifie chaque vitre. Le rouge n’écrase pas le bleu. Le jaune laisse une place au violet. Le vert et le rose se reflètent sans se confondre. Elle ne cherche plus la couleur parfaite. Elle cherche un ensemble assez souple pour accompagner chaque rêve jusqu’à sa propre maison.`
    ],
    episodes: [
      { headline:'La fenêtre qui respire', emoji:'🌙', mood:'mystery', pace:'normal', scene:`Aya ne dort pas. Sa fenêtre inspire et expire comme si la maison rêvait. Sur le rebord, un chat noir aux moustaches argentées dépose une clé en forme de lune. « Je m’appelle Ombre. Le Phare des Rêves s’est éteint, et les cauchemars ne trouvent plus la sortie. » Au loin, sur une île, la tour sombre penche sous un ciel rempli de lits volants. Aya enfile sa cape indigo. Une barque de papier l’attend, mais deux courants partent vers l’île : l’un brille de lucioles joyeuses ; l’autre est silencieux, marqué par des bouées qui semblent inquiètes. Ombre affirme que les deux connaissent un passage.`, question:'Quel courant Aya choisit-elle ?', choices:[choice('Suivre les lucioles joyeuses','✨','suivre',`Les lucioles filent vite et entraînent la barque dans une ronde étincelante. Aya rit, puis remarque qu’elles tournent pour éviter un rocher triste. Elle ralentit et leur demande d’éclairer aussi ce qui fait moins envie. Ensemble, elles découvrent l’entrée sûre du port.`), choice('Écouter les bouées inquiètes','🔔','ecouter',`Chaque bouée sonne avant une vague cachée. Aya compte les tintements et guide la barque entre les rochers. Son inquiétude ne disparaît pas, mais elle devient une carte précise. Ombre admet que la prudence peut être courageuse.`)]},
      { headline:'La salle de la joie débordante', emoji:'🟡', mood:'joy', pace:'lively', scene:`Dans le phare, des ballons jaunes bondissent contre le plafond. Ils rient si fort qu’ils empêchent une petite joie tranquille de parler. La première vitre de la lanterne est vide. Sur un pupitre, une énigme dit : « La joie éclaire quand elle peut circuler. » Aya pourrait ouvrir les fenêtres pour laisser les ballons danser dehors, ou inviter chacun à raconter une seule chose heureuse, à tour de rôle. Ombre pourchasse sa propre queue au milieu des rebonds et finit coincé dans un ballon. « Très drôle », marmonne-t-il, ce qui fait rire Aya encore plus.`, question:'Comment rendre la joie lumineuse sans qu’elle écrase tout ?', choices:[choice('Ouvrir un espace pour danser','🪟','explorer',`Aya ouvre les grandes fenêtres. Les ballons s’élancent autour du phare au lieu de se cogner entre eux. La petite joie tranquille peut enfin se poser dans la lanterne. Elle explique qu’une joie partagée a besoin d’espace, pas forcément de bruit.`), choice('Partager les joies à tour de rôle','🗣️','partager',`Aya donne la parole avec la clé-lune comme bâton de parole. Chaque ballon raconte une joie, puis écoute celle du suivant. Ombre avoue qu’il aime les couvertures encore chaudes. Leur rire devient doux, et une lumière jaune remplit la première vitre.`)]},
      { headline:'Le couloir des colères rouges', emoji:'🔴', mood:'suspense', pace:'lively', scene:`Le couloir suivant est barré par des flammes rouges qui crient : « Ce n’est pas juste ! » Elles ne brûlent pas la peau, mais poussent les meubles et claquent les portes. Au centre, un petit rêve en armure serre les poings parce qu’on lui a pris son tour. Aya sent sa propre colère arriver : elle aussi déteste être bousculée. Pour retrouver la vitre rouge, elle peut aider le rêve à dire clairement ce qui s’est passé, ou lui proposer de décharger l’énergie en poussant un énorme coussin contre le mur. Il faudra ensuite chercher une réparation juste.`, question:'Que fait Aya avec cette colère ?', choices:[choice('Mettre des mots précis','💬','demander',`Aya demande : « Qu’est-ce qui s’est passé ? De quoi as-tu besoin maintenant ? » Le rêve desserre ses poings et raconte. Les flammes deviennent des rubans rouges. Ensemble, ils écrivent une demande ferme mais sans insulte : récupérer son tour et recevoir des excuses.`), choice('Pousser le coussin-tempête','💪','courage',`Aya et le rêve poussent le coussin de toutes leurs forces. Ombre compte jusqu’à dix. L’énergie rouge cesse de renverser les meubles ; elle devient assez calme pour parler. Le rêve peut alors proposer une règle de tours que chacun comprendra.`)]},
      { headline:'Le jardin de la tristesse bleue', emoji:'🔵', mood:'sadness', pace:'slow', scene:`Derrière une porte humide s’étend un jardin sous la pluie. Une fillette de brume tient un cerf-volant déchiré. Elle voudrait que tout le monde parte pour pouvoir pleurer sans être vue. Chaque larme fait pousser une fleur bleue, mais elle les arrache aussitôt, honteuse. Aya pense à une chose qu’elle a perdue un jour et sent sa gorge se serrer. Elle peut s’asseoir sans parler, juste assez près pour que la fillette ne soit pas seule, ou l’aider à fabriquer un petit bateau où déposer le souvenir du cerf-volant.`, question:'Comment Aya accompagne-t-elle la tristesse ?', choices:[choice('Rester près d’elle en silence','🫶','attendre',`Aya s’assoit sous la pluie. Elle ne dit ni « ce n’est rien » ni « souris ». Ombre se roule contre les bottes de la fillette. Peu à peu, celle-ci laisse les fleurs pousser. Une larme devient la vitre bleue, claire comme une goutte après l’orage.`), choice('Construire un bateau-souvenir','⛵','inventer',`Aya plie une page de son carnet et la fillette y dessine le cerf-volant. Elles posent le bateau sur une flaque ; il emporte le dessin sans effacer le souvenir. Les fleurs bleues s’ouvrent et offrent à la lanterne une lumière tendre.`)]},
      { headline:'La bibliothèque des peurs violettes', emoji:'🟣', mood:'gentle_fear', pace:'slow', scene:`Des livres chuchotent dans le noir : peur de se perdre, peur du bruit, peur de décevoir. Chaque couverture grandit dès qu’on lui tourne le dos. Aya cherche la peur utile, celle qui montre un danger réel, mais les histoires parlent toutes ensemble. Elle peut allumer une petite veilleuse et lire les titres un par un, ou demander à Ombre de raconter sa propre peur pour montrer que personne n’est seul. Le chat hérisse ses moustaches : il préférerait combattre un dragon. Pourtant, une ombre immense rampe déjà entre les rayons.`, question:'Comment réduire le noir sans nier la peur ?', choices:[choice('Examiner les peurs une par une','🔍','observer',`À la veilleuse, Aya trie les livres : danger réel, imagination, souvenir. Quand une peur est nommée, sa couverture reprend une taille normale. L’ombre n’était qu’un manteau suspendu. La vitre violette apparaît dans un ouvrage intitulé « Prudence ».`), choice('Inviter Ombre à parler','🐈','partager',`Ombre avoue qu’il a peur de ne pas être un guide assez courageux. Dire la vérité ne le rapetisse pas ; au contraire, sa silhouette redevient normale. Les livres se taisent pour écouter. Une lueur violette se pose sur sa moustache puis rejoint la lanterne.`)]},
      { headline:'Le balcon de l’envie verte', emoji:'🟢', mood:'mystery', pace:'normal', scene:`Sur un balcon poussent des plantes qui copient tout. L’une veut les pétales de sa voisine, l’autre sa hauteur, une troisième jalouse même les épines du rosier. À force d’imiter, elles oublient leurs propres graines. Une petite fougère rêve d’éclairer comme la lanterne d’Aya. Aya peut lui montrer ce qu’elle sait déjà faire — offrir de l’ombre fraîche — ou organiser un échange où chaque plante prête une qualité sans perdre la sienne. Le vent des rêves se lève ; les tiges vertes s’emmêlent autour de l’escalier.`, question:'Comment transformer l’envie en inspiration ?', choices:[choice('Chercher la force unique de chacune','🌿','observer',`Aya demande à chaque plante ce qu’elle offre déjà. La fougère protège les jeunes pousses, le rosier abrite les oiseaux, la mousse garde l’eau. En reconnaissant leurs forces, les tiges cessent de copier. Une pousse verte dessine la cinquième vitre.`), choice('Créer un jardin d’échanges','🌱','partager',`Les plantes partagent graines, conseils et lumière, sans arracher leurs racines. La fougère reçoit un cristal qui reflète la lanterne et offre en retour son ombre fraîche. L’envie devient une idée : apprendre de l’autre sans vouloir devenir l’autre.`)]},
      { headline:'La tache sans couleur', emoji:'⬛', mood:'gentle_fear', pace:'normal', scene:`La grande tache bloque maintenant tout le palier. Elle murmure avec la voix d’Aya : « Et si tu te trompais ? Et si tout le monde riait ? » C’est la honte, cachée si longtemps qu’elle a perdu sa couleur. Aya se souvient du jour où elle a donné une mauvaise réponse devant la classe et voulu disparaître. Elle peut dessiner cette scène sur le mur puis y ajouter ce qu’elle aurait aimé entendre, ou la raconter à Ombre, qui promet d’écouter sans plaisanter. La tache attend ; elle ne veut plus effrayer, seulement être reconnue.`, question:'Comment Aya rend-elle une forme à ce souvenir ?', choices:[choice('Redessiner la scène avec douceur','🖍️','inventer',`Aya dessine son erreur, puis ajoute une bulle : « Se tromper n’enlève rien à ta valeur. » Elle dessine aussi une porte de sortie et une amie qui sourit gentiment. La tache devient rose, couleur de la compassion que l’on peut s’offrir à soi-même.`), choice('Raconter la vérité à Ombre','🤫','partager',`Aya raconte tout, même la chaleur dans ses joues. Ombre ne plaisante pas. Il dit seulement : « J’aurais aimé être là pour m’asseoir près de toi. » La honte rétrécit quand elle n’est plus secrète et devient une vitre rose très douce.`)]},
      { headline:'L’escalier des surprises orange', emoji:'🟠', mood:'wonder', pace:'lively', scene:`Les marches se changent sans prévenir : plume, trampoline, flaque, nuage. C’est la surprise orange, parfois délicieuse, parfois désagréable. Aya veut atteindre le sommet sans contrôler chaque marche. Elle peut avancer en testant du bout du pied et en adaptant son équilibre, ou inventer avec Ombre un signal drôle à crier chaque fois que le sol change. Un groupe de rêves-papillons les suit ; s’ils paniquent, le vent les dispersera. S’ils apprennent à se réorienter, ils pourront tous monter.`, question:'Comment apprivoiser l’imprévu ?', choices:[choice('Tester, observer, puis avancer','🦶','observer',`Aya touche chaque marche avant d’y poser son poids. Elle ne sait pas ce qui vient, mais elle sait quoi faire ensuite : regarder, respirer, choisir. Les papillons imitent sa méthode. Une marche orange se détache et devient la sixième vitre.`), choice('Inventer le cri « Hop, changement ! »','📣','chanter',`À chaque transformation, toute la troupe crie : « Hop, changement ! » Même quand Aya tombe dans un coussin de mousse, elle peut rire puis se relever. Le signal n’empêche pas l’imprévu ; il rappelle qu’ils peuvent y répondre ensemble.`)]},
      { headline:'La salle de la fierté dorée', emoji:'🟨', mood:'triumph', pace:'normal', scene:`Au sommet, des miroirs montrent Aya couronnée, applaudie, plus brillante que tout le monde. Une voix promet d’allumer la dernière vitre si elle affirme avoir réussi seule. Ombre baisse les oreilles : sans lui, elle ne serait pas arrivée, mais sans ses choix à elle, lui non plus. Aya distingue derrière les miroirs tous les rêves aidés en chemin. Elle peut briser l’illusion en nommant la contribution de chacun, ou retourner les miroirs afin qu’ils montrent les efforts plutôt que les récompenses. La fierté n’a pas besoin de mentir pour être belle.`, question:'Quelle fierté Aya veut-elle garder ?', choices:[choice('Remercier chaque compagnon','🙏','partager',`Aya cite Ombre, les bouées, les ballons, la fillette de brume et même sa peur prudente. Les couronnes s’effacent ; une lumière dorée reste pourtant autour d’elle. Elle est fière d’avoir choisi, et reconnaissante d’avoir été aidée.`), choice('Montrer les efforts dans les miroirs','🪞','observer',`Aya retourne les miroirs. Ils montrent ses hésitations, ses respirations, ses erreurs corrigées et les pattes tremblantes d’Ombre. Ce chemin réel brille bien plus que la couronne. La septième vitre, dorée, rejoint la lanterne.`)]},
      { headline:'Le choix de la gardienne', emoji:'🌈', mood:'triumph', pace:'normal', final:true, scene:`Les sept couleurs tournent dans la grande lentille : jaune, rouge, bleu, violet, vert, rose, orange et l’éclat doré qui les relie. Le phare reconnaît qu’aucune émotion ne doit régner seule. Pourtant, les rêves sont toujours dispersés au-dessus de la mer. Aya doit choisir une façon de les guider. Un faisceau direct atteindra vite toutes les maisons. Une constellation laissera à chacun une carte pour les nuits futures. Une ronde de lanternes demandera aux habitants de s’aider, mais elle créera de nouveaux gardiens. Ombre pose la clé-lune dans la paume d’Aya. « La bonne lumière sera celle que tu prends le temps de porter. »`, question:'Comment Aya rallume-t-elle le Phare des Rêves ?', choices:[choice('Envoyer un grand faisceau arc-en-ciel','🌈','courage',`Aya place toute la lanterne dans la lentille. Un faisceau traverse la mer, touche chaque fenêtre et ouvre une sortie lumineuse à chaque cauchemar. Les rêves retrouvent aussitôt leurs dormeurs.`), choice('Dessiner une constellation des émotions','🌌','inventer',`Aya projette chaque couleur dans le ciel et les relie avec la clé-lune. La constellation forme une carte : écouter, respirer, demander de l’aide, choisir. Les rêves apprennent à s’orienter même loin du phare.`), choice('Partager des lanternes dans le village','🏮','partager',`Aya divise la lumière sans la diminuer. Chaque habitant reçoit une petite lanterne et apprend le refrain. De maison en maison, les couleurs forment une ronde qui ramène doucement les rêves.`)]}
    ],
    endings:[
      { title:'La grande lumière', emoji:'🌈', text:`Le faisceau fait un tour complet du monde des rêves. Les cauchemars trouvent une porte de sortie et deviennent de simples nuages qui se dissolvent au matin. Aya rentre juste avant que sa fenêtre cesse de respirer. Sur son oreiller dort Ombre, roulé autour de la clé-lune. Désormais, quand une émotion devient trop grande, Aya imagine les sept vitres. Elle n’a pas besoin d’éteindre ce qu’elle ressent pour retrouver son chemin.` },
      { title:'La carte du ciel intérieur', emoji:'🌌', text:`La constellation reste visible aux enfants qui ferment les yeux et respirent lentement. Chaque étoile porte une question bienveillante : « Que ressens-tu ? Que veut protéger cette émotion ? Quel geste choisis-tu ? » Ombre devient gardien officiel de la carte, même s’il s’endort souvent pendant son service. Aya garde une petite étoile rose dans sa poche. Elle brille chaque fois qu’elle se parle avec douceur.` },
      { title:'Le village aux mille gardiens', emoji:'🏮', text:`Toute la nuit, les habitants se passent les lanternes. Personne n’est obligé de garder seul le phare. La fillette de brume cultive le bleu, le rêve en armure veille sur le rouge, et Ombre enseigne la peur courageuse avec beaucoup de gestes théâtraux. Aya devient la première Gardienne qui sait demander du relais. Au matin, chaque fenêtre du village reflète une couleur différente, et ensemble elles éclairent plus loin que l’ancien faisceau.` }
    ]
  },
  {
    id:'malo-agence-astronautes', title:'Malo et l’Agence des Animaux Astronautes', coverEmoji:'🚀',
    coverImage:'./assets/stories/malo-agence-astronautes/cover.jpg', ageRange:'5–9 ans', ageBand:'5-9', heroVoice:'male', durationMinutes:20,
    intro:'La Lune a perdu son rire et commence à s’éloigner. Malo embarque avec un raton laveur, une chouette et un gecko pour mener l’enquête.',
    bible:{ premise:'Une équipe d’animaux astronautes enquête sur le rire volé de la Lune.', theme:'Les différences font une équipe', values:['coopération','raisonnement','humour bienveillant'], heroGoal:'Retrouver le rire lunaire avant qu’elle ne quitte son orbite.', stakes:'Les marées et les animaux nocturnes perdront leur repère.', recurringObjects:['le vaisseau Gland-1','la loupe à gravité','le carnet de Malo','le rire hic-hic-hou'] },
    transitions:[
      'Malo note l’indice dans son carnet. Roussette le raton laveur veut déjà accuser quelqu’un, mais Chouette Nova rappelle : « Une piste n’est pas une preuve. » Géo le gecko colle l’indice au tableau avec sa patte et Gland-1 met le cap sur la prochaine balise.',
      'La Lune s’éloigne encore d’un petit kilomètre. Les étoiles paraissent inquiètes, mais l’équipage transforme la pression en plan : ce qu’ils savent, ce qu’ils supposent, ce qu’ils doivent vérifier. Malo trace trois colonnes bien nettes.',
      'Le moteur fait pouet au lieu de vroum. Roussette prétend que c’est prévu ; personne ne le croit. Pourtant ce son absurde déclenche un minuscule écho : hic… hic… quelque part devant eux. Le rire lunaire n’est peut-être pas volé, seulement coincé.',
      'Géo déroule sa langue pour attraper une vis flottante. Nova calcule la trajectoire, Roussette fouille les recoins, Malo relie les idées. Aucun d’eux n’aurait réussi seul. Leur prochain indice pulse sur la carte comme un grain de maïs prêt à éclater.',
      'Une transmission inconnue répète leur propre voix avec dix secondes de retard. Malo résiste à l’envie de répondre trop vite. En écoutant jusqu’au bout, l’équipe distingue derrière l’écho un bruit de grelot venu de la face cachée de la Lune.',
      'Le carnet de Malo est presque rempli. Plusieurs suspects avaient caché quelque chose, mais aucun ne voulait blesser la Lune. Le mystère ressemble moins à un vol qu’à une suite de maladresses. Il reste à comprendre comment les réparer.',
      'Gland-1 traverse une pluie de poussière argentée. Chaque grain porte un souvenir drôle oublié par quelqu’un. L’équipage en attrape quelques-uns, puis les relâche : un souvenir n’est pas une preuve à garder, seulement une lumière pour avancer.',
      'Sur la face cachée, une porte ronde refuse les codes compliqués. Elle s’ouvre seulement quand chacun produit un son différent au même rythme. Malo tape, Nova hulule, Géo claque de la langue et Roussette improvise un solo de casseroles.',
      'Derrière la porte se trouve la machine à marées, bloquée par une énorme bulle transparente. À l’intérieur tourbillonne le rire de la Lune. La bulle grossit dès qu’on se moque de quelqu’un et rétrécit quand on rit avec lui.',
      'La bulle est presque ouverte. Il reste à rendre le rire sans qu’il s’échappe dans l’espace. L’équipe peut le guider par une chaîne de sons, le transporter dans Gland-1 ou inviter la Lune à rire elle-même en découvrant toute la vérité.'
    ],
    reflections:[
      `Avant de décoller, Malo vérifie trois fois les ceintures. Roussette trouve cela peu spectaculaire, jusqu’à ce que son siège se retourne tout seul. Géo répare le verrou et Nova félicite Malo : dans l’espace, la prudence fait partie de l’aventure. Une bonne enquête commence par ramener tout le monde entier, y compris les chaussettes.`,
      `Les hamsters offrent un biscuit à chaque membre de l’équipe. Roussette cache le sien dans une poche déjà pleine de boulons, puis oublie laquelle. Malo inscrit leur témoignage sans supprimer les premiers doutes : être innocent sur une piste ne répond pas encore à toutes les questions. Ils repartent avec des faits, pas avec une conclusion trop grande.`,
      `L’otarie essaie un nouveau numéro et rate sa troisième planète en mousse. Cette fois, la troupe applaudit l’effort avant le résultat. Malo note que le silence du cirque n’était pas seulement un indice : c’était aussi une tristesse à réparer. La mission avance mieux quand on laisse derrière soi un endroit un peu moins seul.`,
      `La comète leur confie une note minuscule qu’elle n’osait jamais chanter. Nova la place dans la carte sonore ; elle correspond exactement à la vibration enregistrée près du satellite. Une pièce du mystère se fixe. Géo rappelle cependant qu’une correspondance n’explique pas encore qui a créé la bulle, ni pourquoi elle attire les rires.`,
      `Pendant que les robots ouvrent la barrière, Malo leur apprend l’expression « donner un coup de main ». Ils essaient aussitôt de lui détacher la main. Toute l’équipe éclate de rire, puis reformule patiemment. Le petit incident rappelle que les mêmes mots ne fabriquent pas toujours la même image dans toutes les têtes.`,
      `Zib rend à Roussette son ricanement perdu. Il lui saute dans la gorge et ressort en éternuement. Roussette rit d’elle-même, puis demande à Zib si elle peut rire aussi. Ce simple « est-ce que ça te va ? » change l’ambiance. Malo ajoute dans son carnet : rire ensemble rapproche ; rire contre quelqu’un ferme les portes.`,
      `Un souvenir de Malo apparaît malgré lui : sa première maquette de fusée s’était écroulée avant le décollage. Il autorise ses amis à la regarder. Nova remarque le moteur déjà ingénieux ; Géo admire les morceaux récupérables. Le souvenir reste embarrassant, mais il montre aussi le début du chemin qui l’a mené jusqu’à Gland-1.`,
      `Une fois la porte ouverte, chacun essaie le son d’un autre et découvre que ce n’est pas si facile. Nova ne sait pas faire pouet, Roussette hulule comme une théière, et la langue de Malo ne colle absolument rien. Ils rient sans classer les talents. Puis chacun reprend sa vraie spécialité pour avancer.`,
      `Malo photographie les conduits abîmés et envoie le diagnostic aux habitants qui avaient lancé les blagues. Tous proposent de réparer. Reconnaître une responsabilité partagée ne signifie pas que personne n’est responsable ; cela signifie que chacun peut prendre une part précise de la solution au lieu de chercher une seule personne à punir.`,
      `La Lune se rapproche juste assez pour entendre. Son visage paraît sérieux, mais pas fâché. Malo prépare son rapport : ce qu’ils ont observé, les erreurs commises, les excuses déjà données et la réparation installée. Dire toute la vérité risque de décevoir un instant. La cacher risquerait de casser la confiance beaucoup plus longtemps.`
    ],
    episodes:[
      {headline:'L’appel de la Lune muette',emoji:'🌙',mood:'mystery',pace:'lively',scene:`À 22 h 02, le réveil de Malo clignote : « Mission urgente. Apporte une chaussette propre. » Dans le jardin l’attend Gland-1, un vaisseau en forme de gland piloté par Roussette, raton laveur spécialiste des boutons qu’il ne faut pas toucher. Nova la chouette dirige l’enquête, et Géo le gecko répare tout avec sa langue collante. La Lune ne rit plus. Sans son fameux « hic-hic-hou », elle s’éloigne et les marées se dérèglent. Sur le toit, Malo trouve deux indices : une poudre argentée menant à l’observatoire et une vibration rigolote provenant d’un satellite-poubelle.`,question:'Quelle piste vérifier en premier ?',choices:[choice('Analyser la poudre à l’observatoire','🔭','observer',`Sous la loupe à gravité, la poudre révèle des empreintes de bottes minuscules et des miettes de biscuit étoilé. Nova identifie les livreurs martiens, mais Malo remarque que les traces vont dans les deux sens : ils ont peut-être apporté quelque chose plutôt que volé le rire.`),choice('Interroger le satellite-poubelle','🛰️','demander',`Le satellite avale les questions et recrache les réponses à l’envers. Géo retourne l’enregistrement : « J’ai vu une bulle filer vers Mars, poursuivie par un camion de livraison. » Une piste utile, mais rien ne prouve que la bulle contenait le rire.`)]},
      {headline:'Les livreurs de biscuits étoiles',emoji:'🍪',mood:'joy',pace:'lively',scene:`Le camion martien roule sur un anneau de Saturne comme sur une autoroute. Ses conducteurs, deux hamsters en casque, reconnaissent les miettes. Ils livraient à la Lune un biscuit spécial pour son anniversaire, mais une bulle géante a aspiré leur klaxon et leur bon de livraison. Roussette trouve cela très suspect. Malo préfère vérifier : le paquet est encore scellé, le camion possède une caméra, et les hamsters proposent d’aider à suivre la bulle. On peut examiner l’enregistrement image par image ou faire rejouer exactement leur trajet.`,question:'Comment Malo vérifie-t-il leur histoire ?',choices:[choice('Regarder la caméra au ralenti','🎥','observer',`Les images montrent la bulle rebondir sur le camion puis emporter seulement le son du klaxon. Dans son reflet, Malo aperçoit une antenne en forme de grelot. Les hamsters disaient vrai. Roussette raye leur nom de sa liste avec un air déçu mais honnête.`),choice('Rejouer le trajet avec le camion','🛻','suivre',`Gland-1 suit le camion à la même vitesse. Au virage, une onde invisible fait vibrer tous les objets drôles. Le klaxon de secours s’envole presque. Malo mesure l’onde : elle attire les sons qui déclenchent le rire, pas les biscuits.`)]},
      {headline:'Le cirque sans applaudissements',emoji:'🎪',mood:'sadness',pace:'normal',scene:`L’antenne-grelot mène à un petit cirque installé sur un astéroïde. Les artistes flottent en silence. Une otarie jongle avec des planètes en mousse ; personne n’applaudit, car la bulle a aspiré tous les bravos. Le directeur, un lapin très sérieux, nie avoir touché au rire lunaire. Pourtant une cage vide porte l’étiquette « Éclats de rire ». Malo peut fouiller les coulisses avec Roussette ou demander au directeur d’expliquer l’étiquette devant toute la troupe. Une accusation trop rapide pourrait fermer la seule piste.`,question:'Quelle méthode choisit l’équipe ?',choices:[choice('Inspecter les coulisses discrètement','🔎','observer',`Roussette découvre que la cage servait à transporter des enregistrements pour le spectacle, pas des rires vivants. Elle contient un fragment de bulle et un billet pour la Comète-Karaoké. Malo photographie les preuves puis remet chaque objet à sa place.`),choice('Poser une question directe et calme','❓','demander',`Le lapin avoue qu’il collectionnait autrefois les rires du public, jusqu’à comprendre que les enfermer les rendait tristes. Il offre son dernier enregistrement : on y entend la bulle fredonner en direction de la Comète-Karaoké.`)]},
      {headline:'La comète qui chante faux',emoji:'☄️',mood:'joy',pace:'lively',scene:`La Comète-Karaoké traverse le système solaire en chantant beaucoup trop fort et rarement juste. Elle a avalé par accident une partie des sons joyeux attirés par la bulle. Pour parler, il faut suivre son refrain ou couper son micro cosmique pendant trois secondes. Nova préfère calculer la bonne note ; Roussette veut appuyer sur le gros bouton rouge. Malo remarque que la comète rougit chaque fois qu’on rit d’elle. Peut-être chante-t-elle plus fort pour cacher sa gêne. Il faut obtenir l’indice sans transformer sa maladresse en plaisanterie méchante.`,question:'Comment approcher la comète ?',choices:[choice('Chanter avec elle sans se moquer','🎤','chanter',`Malo trouve une note confortable et l’équipe crée des harmonies autour de la comète. Elle ralentit, soulagée de ne plus devoir impressionner. Elle raconte que la bulle cherchait « la machine qui fait monter et descendre » sur la Lune.`),choice('Demander une pause technique','⏸️','demander',`Au lieu de couper brutalement le micro, Malo propose une pause pour vérifier le son. Dans le silence, la comète entend enfin le grelot de la bulle. Elle indique sa direction et remercie l’équipe de ne pas avoir ri contre elle.`)]},
      {headline:'Le péage des robots littéraux',emoji:'🤖',mood:'mystery',pace:'normal',scene:`Pour rejoindre la Lune, Gland-1 doit passer un péage tenu par trois robots qui comprennent tout au pied de la lettre. « Donnez votre mot de passe », ordonnent-ils. Roussette tend le carnet : « Voilà notre mot. » Alarme. Nova dit qu’ils sont pressés : les robots apportent une presse à papier. Nouvelle alarme. Malo peut résoudre leur devinette logique, ou reformuler chaque phrase de manière très précise. Derrière eux, la Lune s’éloigne encore. Géo se prépare à coller le vaisseau au péage si le courant gravitationnel devient trop fort.`,question:'Comment éviter les malentendus ?',choices:[choice('Résoudre la devinette des trois portes','🧩','inventer',`Malo compare les symboles : une porte ment, une dit vrai, une répète la précédente. Il pose une seule question et trouve le passage bleu. Les robots tamponnent le carnet : « Raisonnement agréé, niveau noisette supérieure. »`),choice('Parler avec des phrases très précises','🗨️','demander',`Malo explique le but, la destination et l’urgence sans expression imagée. Les robots comprennent enfin et ouvrent une voie prioritaire. Ils ajoutent même que la bulle a demandé l’accès à la machine des marées vingt minutes plus tôt.`)]},
      {headline:'Le faux coupable de la face claire',emoji:'👽',mood:'suspense',pace:'normal',scene:`Près du cratère du Sourire, l’équipe trouve Zib, une minuscule extraterrestre avec l’antenne-grelot aperçue dans les reflets. Elle cache un sac qui glousse. Roussette triomphe : « Coupable ! » Mais Zib tremble et explique qu’elle ramassait seulement les petits rires perdus pour les rendre à leurs propriétaires. Dans le sac, chaque gloussement porte un nom. Aucun n’appartient à la Lune. Malo peut vérifier la collection avec la loupe à gravité, ou offrir à Zib une place dans l’équipe pour qu’elle montre où la grande bulle est passée.`,question:'Comment traiter cette suspecte évidente ?',choices:[choice('Vérifier avant de décider','⚖️','observer',`La loupe confirme que les rires du sac viennent du cirque, des hamsters et même de Roussette, qui avait perdu un petit ricanement mardi. Zib n’est pas coupable. Honteuse de son accusation, Roussette présente des excuses précises.`),choice('L’inviter à guider l’enquête','🧭','aider',`Zib rend d’abord tous les rires puis grimpe dans Gland-1. Son antenne détecte les sons captifs. Elle révèle que la grande bulle s’est glissée sous la surface, près de la machine des marées.`)]},
      {headline:'La pluie de souvenirs drôles',emoji:'😂',mood:'wonder',pace:'lively',scene:`Sur la face sombre, une pluie argentée montre des souvenirs amusants : la première chute de Géo dans un pot de confiture, Nova portant ses lunettes à l’envers, Malo disant « bonjour » à un lampadaire. Roussette veut tout enregistrer pour une future soirée. Mais certains souvenirs appartiennent aux autres et les gênent encore. Au milieu des images se cache la trajectoire de la bulle. L’équipe peut regarder sans conserver, en demandant la permission pour chaque souvenir, ou fermer les yeux et suivre seulement le son du grelot.`,question:'Comment respecter les souvenirs tout en avançant ?',choices:[choice('Demander avant de regarder','🙋','demander',`Chacun autorise certains souvenirs et en garde d’autres privés. En les triant ensemble, ils voient la bulle frôler une vieille bouche d’aération. Roussette efface aussitôt les images non autorisées, même les plus drôles.`),choice('Suivre le grelot les yeux fermés','👂','ecouter',`Attachés par une corde, ils avancent au son : tin… tin… TIN. Sans les images, personne n’est exposé. Géo sent sous ses pattes une grille qui vibre ; l’entrée de la machine se trouve juste dessous.`)]},
      {headline:'La porte-orchestre',emoji:'🥁',mood:'joy',pace:'lively',scene:`La porte de la machine n’a ni poignée ni clavier. Quatre cercles s’allument : grave, aigu, sec, doux. Nova comprend qu’elle attend une équipe, pas un mot de passe. Malo peut diriger un rythme où chacun garde son son, ou demander à tous d’imiter le même bruit pour simplifier. Le premier essai devra être précis : une erreur déclenche un aspirateur à poussière lunaire déjà tourné vers leurs chaussures. Roussette serre sa chaussette de secours comme un trésor.`,question:'Quelle musique ouvre la porte ?',choices:[choice('Assembler quatre sons différents','🎼','chanter',`Malo tape le rythme, Nova hulule, Géo claque et Roussette secoue ses outils. Les différences s’emboîtent comme les pièces d’une machine. La porte reconnaît l’harmonie et s’ouvre sans aspirer une seule chaussette.`),choice('Commencer ensemble puis créer des solos','🥁','partager',`Ils frappent d’abord le même battement rassurant, puis chacun ajoute son motif. L’aspirateur hésite, se met à danser et s’éteint. La porte s’ouvre sur une salle remplie de tuyaux et de petits rires coincés.`)]},
      {headline:'La vérité dans la machine à marées',emoji:'⚙️',mood:'suspense',pace:'normal',scene:`La machine a fabriqué la bulle par accident. Lors de l’anniversaire de la Lune, chacun a voulu envoyer une blague en même temps. Surchargée, la conduite des rires a gonflé, aspiré les sons joyeux et bouché le régulateur des marées. Personne n’est un voleur ; tout le monde a contribué au problème sans le savoir. Pour libérer le rire, l’équipe peut répartir les sons dans plusieurs petits conduits, ou couper la machine quelques secondes et pousser la bulle manuellement. La première méthode demande coordination ; la seconde, confiance et force.`,question:'Comment réparer la machine ?',choices:[choice('Répartir les sons avec précision','🔧','inventer',`Nova calcule, Géo branche, Zib écoute et Malo donne le rythme. Roussette résiste héroïquement au gros bouton rouge. La pression baisse conduit après conduit. La bulle rétrécit jusqu’à tenir entre quatre pattes.`),choice('Arrêter puis pousser tous ensemble','🛑','aider',`Malo compte à rebours. Dans le silence spatial, tous poussent la bulle vers la sortie. Même la Lune semble retenir son souffle. La machine redémarre juste à temps, plus stable, tandis que le rire flotte enfin libre devant eux.`)]},
      {headline:'Rendre son rire à la Lune',emoji:'🌕',mood:'triumph',pace:'normal',final:true,scene:`Le rire libéré ressemble à un ruban d’or qui fait « hic-hic-hou ». Mais il est fragile : un éclat trop brusque le disperserait pour toujours. Malo peut organiser une chaîne où chaque membre transmet une note jusqu’à la Lune, enfermer doucement le ruban dans Gland-1 pour le livrer au cœur du cratère, ou raconter toute l’enquête à la Lune afin qu’elle retrouve elle-même l’envie de rire. Les marées attendent. Le cirque, les hamsters, la comète et même les robots suivent la mission sur leurs écrans. Cette fois, personne ne cherche à être le héros unique.`,question:'Comment l’équipe rend-elle le rire lunaire ?',choices:[choice('Créer une chaîne de sons','🎶','chanter',`Chaque membre reçoit une partie du « hic-hic-hou » et la transmet au suivant sans la déformer. Le ruban grandit à chaque différence bien accordée, puis rejoint la Lune comme une musique d’équipe.`),choice('Le transporter dans Gland-1','🚀','courage',`Géo transforme la cabine en boîte à musique étanche. Malo pilote très doucement jusqu’au cratère du Sourire. Roussette ouvre la porte au signal exact, et le rire retrouve sa place sans perdre une étincelle.`),choice('Raconter honnêtement toute l’enquête','📖','partager',`Malo raconte les fausses pistes, les excuses et la machine surchargée. La Lune comprend qu’on ne lui avait pas volé sa joie. Son propre rire renaît, rejoint le ruban puis éclate avec tendresse dans tout le ciel.`)]}
    ],
    endings:[
      {title:'L’orchestre orbital',emoji:'🎶',text:`Le « hic-hic-hou » remet la Lune sur son orbite. Les océans respirent de nouveau au bon rythme. Pour remercier l’équipe, la Lune transforme un petit cratère en scène de concert. Malo dirige la première répétition, où chaque son compte, même le pouet du moteur. Roussette reçoit la médaille du bouton qu’elle n’a pas appuyé. C’est, selon elle, la décoration la plus difficile à mériter de toute la galaxie.`},
      {title:'La livraison la plus douce',emoji:'🚀',text:`Gland-1 se pose au centre du cratère et la Lune récupère son rire comme on retrouve un ami. Elle offre à Malo un badge de pilote prudent, à Géo un rouleau de ruban lunaire, à Nova une carte des orbites et à Roussette une boîte contenant un bouton rouge parfaitement inutile. De retour au jardin, Malo entend les vagues au loin. Elles semblent répéter : « Une équipe, une équipe, une équipe. »`},
      {title:'Le rire retrouvé ensemble',emoji:'🌕',text:`La vérité fait d’abord soupirer la Lune, puis sourire, puis rire si fort que les étoiles clignotent. Tous ceux qui avaient envoyé une blague présentent leurs excuses et organisent désormais les messages à tour de rôle. Malo ouvre officiellement l’Agence des Animaux Astronautes aux enfants enquêteurs. Sa première règle tient sur une ligne : « On vérifie avant d’accuser. » La seconde ajoute : « Et on garde toujours une chaussette propre. »`}
    ]
  },
  {
    id:'nino-doudou-voyageur', title:'Nino Ourson et le Doudou Voyageur', coverEmoji:'🧸',
    coverImage:'./assets/stories/nino-doudou-voyageur/cover.jpg', ageRange:'2–5 ans', ageBand:'2-5', heroVoice:'male', durationMinutes:10,
    intro:'Le doudou de Nino a suivi un fil bleu jusque dans le jardin de la lune. Une aventure douce à écouter avant de dormir.',
    bible:{premise:'Nino suit un fil bleu pour retrouver son doudou Plume.',theme:'Grandir en gardant un refuge',values:['patience','entraide','sécurité affective'],heroGoal:'Retrouver Plume et rentrer avant le dernier bâillement.',stakes:'Nino craint de s’endormir sans son doudou, mais reste toujours en sécurité.',recurringObjects:['le fil bleu','Plume le doudou','la chanson petit pas, grand câlin']},
    transitions:[
      'Le fil bleu brille un peu plus. Nino pose une patte sur son cœur. « Petit pas, grand câlin, je suis le fil et je vais bien. » La lune éclaire le prochain bout de chemin.',
      'Quelque part devant, une clochette fait ding-ding. C’est celle de Plume ! Nino sourit. Il n’est pas encore arrivé, mais il sait qu’il va dans la bonne direction.',
      'Nino bâille un tout petit peu. Escargot bâille aussi, beaucoup plus longtemps. Ils rient doucement, puis reprennent le fil sans se presser.',
      'Le jardin sent la menthe et la pluie. Nino entend un froissement familier. Plume n’est plus très loin. Pour continuer, il suffit d’un choix calme et d’un pas après l’autre.',
      'Au bout du fil apparaît une petite porte ronde. Derrière, quelqu’un fredonne leur chanson. Nino reconnaît la voix de Plume et sent son ventre devenir léger.',
      'Plume est là, mais une dernière rafale sépare encore les deux amis. Nino peut l’appeler, demander de l’aide ou préparer un nid doux pour l’accueillir.'
    ],
    episodes:[
      {headline:'Le fil sous l’oreiller',emoji:'🧵',mood:'calm',pace:'slow',scene:`C’est l’heure de dormir. Nino Ourson met son pyjama vert et cherche Plume, son doudou tout doux. Pas dans le lit. Pas sous la chaise. Pas derrière le livre. Sous l’oreiller, Nino trouve un fil bleu qui passe par la fenêtre. Maman Ourse lui donne une petite lanterne et reste tout près de la maison. Dans le jardin, le fil va vers les fleurs ou vers le vieux banc. Nino respire : une fois dedans, une fois dehors.`,question:'Où Nino regarde-t-il d’abord ?',choices:[choice('Près des fleurs qui brillent','🌼','observer',`Les fleurs ouvrent leurs pétales une par une. Dans la dernière, Nino trouve un petit morceau de tissu de Plume. Une coccinelle a vu le doudou passer vers le banc en saluant la lune.`),choice('Sous le vieux banc','🪑','explorer',`Sous le banc dort Escargot, avec le fil bleu enroulé autour de sa coquille. Il se réveille lentement et se souvient : Plume suivait une luciole vers les fleurs. Escargot propose de venir aider.`)]},
      {headline:'La flaque qui reflète la lune',emoji:'🌙',mood:'wonder',pace:'slow',scene:`Le fil traverse une grande flaque. Dans l’eau, la lune ressemble à un bateau rond. Nino ne veut pas mouiller ses chaussons. Des pierres plates forment un chemin, mais certaines bougent un peu. Une grande feuille flotte aussi comme une barque. Escargot peut montrer les pierres solides, ou pousser doucement la feuille. Nino touche sa lanterne. Maman Ourse est visible au loin, sur le pas de la porte. Tout va bien.`,question:'Comment traverser la flaque ?',choices:[choice('Marcher sur les pierres solides','🪨','observer',`Escargot touche chaque pierre avec ses petites cornes. Nino avance : un pas, puis un autre. La dernière pierre fait ploc, mais ses chaussons restent secs. De l’autre côté, le fil bleu l’attend.`),choice('Naviguer sur la feuille-barque','🍃','inventer',`Nino s’assoit au milieu de la feuille. Escargot pousse, très lentement. La lune voyage avec eux dans le reflet. La barque touche l’autre rive sans une seule éclaboussure.`)]},
      {headline:'Le hérisson qui a peur du bruit',emoji:'🦔',mood:'gentle_fear',pace:'slow',scene:`Derrière les herbes, quelque chose fait snif. C’est Picoti le hérisson. La clochette de Plume a fait ding trop fort, alors Picoti s’est roulé en boule. Il a vu le doudou suivre le fil jusqu’au petit bois. Nino peut parler tout bas pour rassurer Picoti, ou s’asseoir près de lui jusqu’à ce qu’il soit prêt. Le vent remue les feuilles, mais la lanterne reste chaude dans la patte de Nino.`,question:'Comment aider Picoti ?',choices:[choice('Chanter tout doucement','🎵','chanter',`Nino chante : « Petit pas, grand câlin… » Sa voix est si douce que Picoti montre un œil, puis son nez. Il fredonne avec eux et indique le chemin du petit bois.`),choice('Attendre près de lui','⏳','attendre',`Nino ne tire pas sur les piquants. Il attend et respire. Escargot attend aussi, ce qu’il sait très bien faire. Picoti se déroule quand il est prêt et leur montre une empreinte de Plume.`)]},
      {headline:'Le bois des petits sons',emoji:'🌳',mood:'mystery',pace:'slow',scene:`Dans le petit bois, on entend toc dans un tronc, frou-frou dans les feuilles et hou-hou très loin. Le fil bleu se partage autour de deux arbres, puis se rejoint. D’un côté, une plume blanche est accrochée à une branche. De l’autre, une clochette brille sous une fougère. Nino sait que les deux peuvent être des indices. Il serre la main de Picoti, qui a choisi de les accompagner.`,question:'Quel indice Nino suit-il ?',choices:[choice('Regarder la plume blanche','🪶','observer',`La plume porte l’odeur douce de Plume le doudou. Un hibou explique qu’il l’a aidé à passer sous la porte ronde. Il montre un raccourci éclairé par des champignons.`),choice('Écouter la clochette','🔔','ecouter',`Ding… ding… La clochette répond quand Nino l’appelle. Elle roule toute seule vers une porte ronde au pied d’un arbre. Derrière la porte, Plume fredonne vraiment.`)]},
      {headline:'La porte du dernier bâillement',emoji:'🚪',mood:'calm',pace:'slow',scene:`La porte ronde est fermée par une poignée trop haute. Juste à côté, une balançoire de lierre peut soulever Nino. Escargot et Picoti peuvent aussi empiler de gros coussins de mousse. Nino bâille : « Haaaa… » C’est peut-être l’avant-dernier bâillement. Derrière la porte, Plume répond avec un bâillement encore plus grand. Personne n’est pressé, mais tout le monde veut préparer un passage sûr.`,question:'Comment ouvrir la porte ?',choices:[choice('Monter avec la balançoire','🌿','courage',`Picoti tient le lierre et Escargot dit quand pousser. Nino monte juste assez haut, tourne la poignée et redescend dans leurs bras. La porte s’ouvre sur un jardin rempli d’oreillers.`),choice('Construire un escalier de mousse','🧱','aider',`Tous apportent un coussin de mousse. Nino teste chaque marche avant de monter. L’escalier est moelleux et solide. Il atteint la poignée, puis aide ses amis à passer.`)]},
      {headline:'Le nid de Plume',emoji:'🤗',mood:'triumph',pace:'slow',final:true,scene:`Au milieu du jardin d’oreillers, Plume est accroché à une branche basse. Il avait suivi le fil bleu pour rapporter à Nino un rêve tout neuf, mais le vent l’a soulevé. Une rafale fait encore danser la branche. Nino peut appeler Plume pour qu’il lâche au bon moment, demander au hibou de le porter, ou construire dessous un grand nid de coussins. La lune attend. Maman Ourse fait signe depuis la fenêtre. Nino sait qu’il retrouvera son lit, son câlin et son sommeil.`,question:'Comment Nino retrouve-t-il Plume ?',choices:[choice('L’appeler au rythme de leur chanson','🎶','chanter',`Nino chante lentement. Au mot « câlin », Plume lâche la branche et tombe juste dans ses bras. Le fil bleu s’enroule autour d’eux comme un ruban.`),choice('Demander l’aide du hibou','🦉','aider',`Le hibou déploie ses ailes sans bruit. Il prend Plume délicatement et le dépose sur la tête de Nino. Tout le monde chuchote merci.`),choice('Préparer un nid très doux','🪹','inventer',`Nino et ses amis empilent les oreillers. Le vent décroche Plume, qui rebondit une fois, deux fois, puis atterrit en riant dans le nid.`)]}
    ],
    endings:[
      {title:'Le câlin au bon moment',emoji:'🤗',text:`Nino rentre en suivant le fil bleu, avec Plume contre son cœur. Maman Ourse remercie tous les amis du jardin. Dans le lit, Plume offre le rêve neuf : une promenade sur un bateau-lune. Nino chante une dernière fois : « Petit pas, grand câlin… » Puis vient le dernier bâillement. La lanterne s’éteint. Bonne nuit, Nino.`},
      {title:'Le vol tout doux',emoji:'🦉',text:`Le hibou raccompagne la petite troupe jusqu’à la fenêtre. Nino garde une plume blanche pour se rappeler qu’il peut demander de l’aide. Plume retrouve sa place sous son menton. Maman Ourse ferme les rideaux, sauf un petit coin pour la lune. Nino inspire, expire et murmure merci. Ses yeux se ferment avant même la fin du dernier bâillement.`},
      {title:'Le lit le plus moelleux',emoji:'🪹',text:`Le nid est si doux que tous les amis s’y reposent une minute. Puis chacun rapporte un petit coussin jusqu’à la chambre de Nino. Son lit devient un bateau de mousse pour Plume et lui. Maman Ourse borde tout le monde, même Escargot qui s’est déjà endormi. Le fil bleu brille encore un instant, puis devient calme. Bonne nuit, petit voyageur.`}
    ]
  },
  {
    id:'lila-fete-couleurs', title:'Lila Loutre et la Fête des Couleurs', coverEmoji:'🎨',
    coverImage:'./assets/stories/lila-fete-couleurs/cover.jpg', ageRange:'2–5 ans', ageBand:'2-5', heroVoice:'female', durationMinutes:10,
    intro:'La mer a perdu ses couleurs juste avant la fête. Lila découvre qu’on peut les réveiller avec des sons, des gestes et beaucoup d’entraide.',
    bible:{premise:'Lila rassemble sons et gestes pour rendre ses couleurs à la mer.',theme:'Créer ensemble',values:['coopération','expression','attention'],heroGoal:'Réveiller trois couleurs avant la fête.',stakes:'La fête serait grise et les petits animaux déçus.',recurringObjects:['le xylophone-coquillage','la chanson plim plam plume','les rubans de couleur']},
    transitions:[
      'Une note colorée entre dans le xylophone : plim ! Lila remue ses moustaches. « Une couleur réveillée, continuons la journée ! » Ses amis frappent doucement le rythme.',
      'Dans l’eau grise apparaît une petite traînée brillante. Elle mène au prochain ami. Lila nage sans éclabousser les bébés poissons et garde le xylophone bien serré.',
      'Le refrain grandit : « Plim, plam, plume, couleur dans l’écume ! » On peut le chanter, le taper ou simplement l’écouter. Chacun participe à sa façon.',
      'Deux couleurs dansent maintenant autour de Lila. Il en manque encore une pour que la fête commence. Au loin, une tortue agite un ruban tout pâle.',
      'La place de corail est proche. Les animaux apportent leurs sons, leurs pas et leurs sourires. Lila comprend que la dernière couleur ne se trouve pas : elle se fabrique ensemble.',
      'Le xylophone brille de toutes ses coquilles. Pour lancer la fête, Lila peut choisir la musique, la danse ou un grand partage de rubans.'
    ],
    episodes:[
      {headline:'La mer toute grise',emoji:'🌊',mood:'wonder',pace:'slow',scene:`Ce matin, Lila Loutre plonge dans la mer. Oh ! Les algues sont grises. Les poissons sont gris. Même son xylophone-coquillage est gris. Ce soir, c’est la Fête des Couleurs. Une petite bulle rouge passe près de son nez : pop ! Puis elle file vers le jardin de corail. Une bulle bleue part vers la grotte qui chante. Lila ne peut pas suivre les deux en même temps. Elle touche une coquille : plim… presque aucun son.`,question:'Quelle bulle Lila suit-elle ?',choices:[choice('La bulle rouge qui danse','🔴','suivre',`La bulle rouge zigzague entre les coraux. Lila bouge comme elle : à gauche, à droite, petit tour. Les coraux se réveillent et tapent un rythme chaud. Une note rouge entre dans le xylophone.`),choice('La bulle bleue qui fredonne','🔵','ecouter',`La bulle bleue chante « plam, plam » dans la grotte. Lila répond doucement. L’écho devient une vague musicale. Une note bleue se pose dans son xylophone.`)]},
      {headline:'Crabi ne veut pas danser',emoji:'🦀',mood:'joy',pace:'normal',scene:`Sur le sable, Crabi regarde ses pinces grises. Il ne veut pas danser comme les autres. Ses pas vont de côté, jamais devant. Lila lui dit que la fête a besoin de toutes les danses. Elle peut apprendre les pas de côté avec lui, ou lui proposer de jouer du tambour pendant qu’elle danse. Crabi lève une pince, puis l’autre. Peut-être qu’il veut essayer, si personne ne se moque.`,question:'Comment Crabi participe-t-il ?',choices:[choice('Inventer la danse de côté','🦀','inventer',`Lila fait un pas de côté. Crabi en fait deux. Bientôt les poissons les imitent. Le sable dessine des lignes orange sous leurs pieds. Crabi sourit : sa danse devient celle de la fête.`),choice('Jouer le rythme avec ses pinces','🥁','chanter',`Clac, clac, pause. Clac, clac, pause. Crabi trouve un rythme parfait. Lila danse dessus. Une petite lumière orange saute du tambour jusque dans le xylophone.`)]},
      {headline:'La tortue au ruban pâle',emoji:'🐢',mood:'calm',pace:'slow',scene:`Tortille la tortue porte un long ruban sans couleur. Elle nage lentement et croit qu’elle arrivera trop tard. Lila peut ralentir pour avancer près d’elle, ou attacher le ruban entre tous les amis afin que chacun le porte un petit peu. La place de la fête se voit au loin. Personne n’a besoin de courir. Le xylophone fait plim et plam, comme deux encouragements.`,question:'Comment accompagner Tortille ?',choices:[choice('Nager à son rythme','🐢','attendre',`Lila reste près de Tortille. Elles regardent les petits poissons, puis respirent à la surface. Le ruban devient vert, couleur du chemin pris sans se presser.`),choice('Porter le ruban tous ensemble','🤝','aider',`Crabi prend un bout, Lila le milieu et les poissons la fin. Tortille nage plus légère. Le ruban se colore en vert tendre et relie toute la petite troupe.`)]},
      {headline:'La grotte des échos timides',emoji:'🎵',mood:'mystery',pace:'slow',scene:`Dans la grotte, un petit hippocampe se cache. Il connaît la note jaune, mais sa voix est minuscule. Quand tout le monde parle, on ne l’entend plus. Lila peut demander un grand silence pour écouter, ou jouer une note très douce afin que l’hippocampe puisse répondre. Crabi range ses pinces derrière son dos. Même les bulles font moins de bruit.`,question:'Comment écouter la petite voix ?',choices:[choice('Faire le silence des oreilles ouvertes','👂','ecouter',`Tout devient calme. On entend : « tin… » L’hippocampe recommence, plus confiant : « TIN ! » Sa note jaune éclaire la grotte et rejoint le xylophone.`),choice('Jouer une note douce avec lui','🎼','chanter',`Lila joue plim. L’hippocampe répond tin. Ensemble : plim-tin, plim-tin. Sa voix n’a pas besoin d’être forte pour compter. Une lumière jaune danse entre eux.`)]},
      {headline:'Le courant qui mélange tout',emoji:'🌀',mood:'suspense',pace:'normal',scene:`Un courant tourne autour de la place de corail. Il mélange les rubans, les instruments et les chapeaux. Rien n’est dangereux, mais tout vole ! Lila peut demander à chacun d’attraper une chose près de lui, ou planter le long ruban vert entre deux rochers pour faire une ligne où se tenir. Les amis se regardent. Ils ont déjà appris à écouter, attendre et aider.`,question:'Comment ranger le tourbillon ?',choices:[choice('Chacun aide près de lui','🫧','aider',`Crabi attrape les chapeaux, Tortille les rubans, l’hippocampe les petites clochettes. Lila récupère le xylophone. Le courant ralentit parce que tout le monde fait une petite part.`),choice('Fabriquer une ligne avec le ruban','〰️','inventer',`Lila attache le ruban vert. Tous s’y tiennent d’une nageoire ou d’une pince. Le courant les fait danser sans les disperser, puis dépose les objets à leurs pieds.`)]},
      {headline:'La couleur de la fête',emoji:'🌈',mood:'triumph',pace:'normal',final:true,scene:`La place est prête. Rouge, bleu, orange, vert et jaune brillent dans le xylophone. Pourtant le grand coquillage de la fête reste gris. Il attend le geste de tous les amis. Lila peut lancer la chanson « Plim, plam, plume », inviter chacun à montrer son mouvement préféré, ou partager les rubans pour dessiner un arc-en-ciel dans l’eau. Crabi lève ses pinces. Tortille déroule son ruban. L’hippocampe prend une grande inspiration.`,question:'Comment commence la Fête des Couleurs ?',choices:[choice('Chanter tous les sons ensemble','🎶','chanter',`Plim, plam, tin, clac ! Les sons se répondent. Le grand coquillage devient rose et envoie des bulles colorées dans toute la mer.`),choice('Faire la danse de chacun','💃','courage',`Un pas de côté, une nage lente, un petit tour et une bulle. Chaque mouvement ajoute une couleur. Le grand coquillage scintille comme un soleil sous l’eau.`),choice('Dessiner avec les rubans','🌈','partager',`Chaque ami tient une couleur. Ils nagent ensemble et tracent un immense arc-en-ciel. Le grand coquillage s’ouvre et lance la fête.`)]}
    ],
    endings:[
      {title:'Le concert de l’écume',emoji:'🎶',text:`Toute la mer chante : « Plim, plam, plume, couleur dans l’écume ! » Les bébés poissons font seulement « bou », et c’est très bien. Lila joue doucement, Crabi garde le rythme et l’hippocampe ose son petit tin. Le soir, les couleurs se reposent dans les coquillages, prêtes à revenir demain.`},
      {title:'La danse de toutes les nageoires',emoji:'💃',text:`Personne ne danse pareil, alors la fête ne ressemble à aucune autre. Tortille avance lentement, Crabi va de côté et Lila tourne sur le dos. Les couleurs suivent chaque mouvement. Quand la musique se calme, tous se saluent. La mer garde un petit reflet doré pour dire merci.`},
      {title:'L’arc-en-ciel sous la mer',emoji:'🌈',text:`Les rubans forment un arc-en-ciel assez grand pour abriter toute la place. Les animaux s’y installent pour partager des fruits de mer en forme d’étoile. Lila accroche le dernier ruban à son xylophone. Chaque fois qu’elle joue plim, une petite couleur revient danser dans l’écume.`}
    ]
  }
];

export default stories;
