import { getSettings } from '../storage/settings.js';
import { logDebug } from '../core/debug.js';
import { getAudioCacheEntry, putAudioCacheEntry } from '../storage/audio_cache.js';

let activeResolve = null;
let currentAudio = null;
let primed = false;

function settle() { if (activeResolve) { activeResolve(); activeResolve = null; } }
function stopAudioElement() { if (currentAudio) { try { currentAudio.pause(); currentAudio.src = ''; } catch {} currentAudio = null; } }
function hashText(value) { let h = 2166136261; for (const ch of String(value)) { h ^= ch.charCodeAt(0); h += (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24); } return (h >>> 0).toString(36); }
function cacheId(provider, voice, model, format, forceFrench, text) { return `${provider}::${voice || 'default'}::${model}::${format}::${forceFrench ? 'fr' : 'auto'}::${hashText(text)}`; }
function blobToDataUrl(blob) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(reader.error); reader.readAsDataURL(blob); }); }
function dataUrlToBlob(dataUrl) { const [meta, base64] = dataUrl.split(','); const mime = /data:(.*?);base64/.exec(meta)?.[1] || 'audio/mpeg'; const bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0)); return new Blob([bytes], { type: mime }); }
async function getCachedBlob(s, text) { const id = cacheId(s.ttsProvider, s.ttsVoice, s.ttsModel, s.ttsFormat, s.ttsForceFrench !== false, text); const entry = await getAudioCacheEntry(id); if (!entry?.dataUrl) return null; logDebug('tts.cache.hit', { id, provider: s.ttsProvider, voice: s.ttsVoice, model: s.ttsModel }); return dataUrlToBlob(entry.dataUrl); }
async function saveCachedBlob(s, text, blob) { const forceFrench = s.ttsForceFrench !== false; const id = cacheId(s.ttsProvider, s.ttsVoice, s.ttsModel, s.ttsFormat, forceFrench, text); await putAudioCacheEntry({ id, provider: s.ttsProvider, voice: s.ttsVoice, model: s.ttsModel, format: s.ttsFormat, forceFrench, textHash: hashText(text), textPreview: String(text).slice(0, 120), dataUrl: await blobToDataUrl(blob), createdAt: Date.now() }); logDebug('tts.cache.store', { id, size: blob.size }); }
async function playBlob(blob, meta) { return new Promise(resolve => { stopSpeak(); const url = URL.createObjectURL(blob); const audio = new Audio(url); currentAudio = audio; activeResolve = resolve; logDebug('tts.audio.start', meta); const done = () => { URL.revokeObjectURL(url); stopAudioElement(); settle(); resolve(); }; audio.onended = done; audio.onerror = done; audio.play().catch(done); }); }
export function stopSpeak() { try { window.speechSynthesis?.cancel(); } catch {} stopAudioElement(); settle(); logDebug('tts.stop', {}); }
export function primeTts() { if (!('speechSynthesis' in window) || primed) return; primed = true; try { const u = new SpeechSynthesisUtterance(' '); u.volume = 0; speechSynthesis.cancel(); speechSynthesis.speak(u); setTimeout(() => speechSynthesis.cancel(), 30); } catch {} }
function pickFrenchVoice() { const voices = speechSynthesis.getVoices(); return voices.find(v => /^fr/i.test(v.lang) && /google|premium|hortense|thomas|amelie|audrey/i.test(v.name)) || voices.find(v => /^fr/i.test(v.lang)) || null; }
function speakBrowser(text) { return new Promise(resolve => { if (!text || !('speechSynthesis' in window)) return resolve(); stopSpeak(); const u = new SpeechSynthesisUtterance(String(text)); u.lang = 'fr-FR'; u.rate = 0.97; u.pitch = 1; const voice = pickFrenchVoice(); if (voice) u.voice = voice; logDebug('tts.browser.start', { voice: voice?.name || null, textPreview: String(text).slice(0, 240) }); u.onend = () => { settle(); resolve(); }; u.onerror = () => { settle(); resolve(); }; activeResolve = resolve; try { speechSynthesis.resume?.(); speechSynthesis.speak(u); } catch { settle(); resolve(); } }); }
async function parseRemoteError(res, prefix) { let detail = ''; try { detail = (await res.text())?.slice(0, 300) || ''; } catch {} return new Error(`${prefix}_${res.status}${detail ? `:${detail}` : ''}`); }
async function fetchOpenAiBlob(text, s) { const res = await fetch('https://api.openai.com/v1/audio/speech', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${s.ttsApiKey}` }, body: JSON.stringify({ model: 'gpt-4o-mini-tts', voice: s.ttsVoice || 'nova', input: text, format: 'mp3' }) }); if (!res.ok) throw await parseRemoteError(res, 'openai_tts'); return res.blob(); }
const ELEVEN_LANG_MODELS = new Set(['eleven_multilingual_v2', 'eleven_flash_v2_5', 'eleven_turbo_v2_5', 'eleven_v3']);
export async function fetchElevenSubscription(apiKey) { if (!apiKey) return { ok: false, error: 'missing_api_key' }; try { const res = await fetch('https://api.elevenlabs.io/v1/user/subscription', { headers: { 'xi-api-key': apiKey } }); if (!res.ok) return { ok: false, error: `subscription_${res.status}` }; const data = await res.json(); return { ok: true, ...data }; } catch (error) { return { ok: false, error: String(error) }; } }
async function fetchElevenBlob(text, s) { const voiceId = s.ttsVoice || ''; const modelId = s.ttsModel || 'eleven_multilingual_v2'; const outputFormat = s.ttsFormat || 'mp3_44100_128'; const forceFrench = s.ttsForceFrench !== false; if (!s.ttsApiKey || !voiceId) throw new Error('missing_elevenlabs_tts_config'); const body = { text, model_id: modelId, output_format: outputFormat, voice_settings: { stability: 0.45, similarity_boost: 0.8 } }; if (forceFrench && ELEVEN_LANG_MODELS.has(modelId)) body.language_code = 'fr'; const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'xi-api-key': s.ttsApiKey, Accept: 'audio/mpeg' }, body: JSON.stringify(body) }); if (!res.ok) throw await parseRemoteError(res, 'elevenlabs_tts'); return res.blob(); }
export async function warmTtsCache(texts = []) { const s = getSettings(); if (s.ttsProvider === 'browser' || !s.ttsApiKey) return { stored: 0, skipped: texts.length }; let stored = 0; let skipped = 0; for (const text of texts.filter(Boolean)) { const cached = await getCachedBlob(s, text); if (cached) { skipped++; continue; } try { const blob = s.ttsProvider === 'openai' ? await fetchOpenAiBlob(text, s) : await fetchElevenBlob(text, s); await saveCachedBlob(s, text, blob); stored++; } catch (err) { logDebug('tts.cache.warm.error', { provider: s.ttsProvider, message: String(err), model: s.ttsModel, voice: s.ttsVoice, textPreview: String(text).slice(0, 120) }); } } return { stored, skipped }; }
export async function speak(text) { const s = getSettings(); if (!text) return; try { if ((s.ttsProvider === 'openai' || s.ttsProvider === 'elevenlabs') && s.ttsApiKey) { const cached = await getCachedBlob(s, text); if (cached) return playBlob(cached, { provider: s.ttsProvider, voice: s.ttsVoice, model: s.ttsModel, format: s.ttsFormat, cached: true, textPreview: String(text).slice(0, 240) }); const blob = s.ttsProvider === 'openai' ? await fetchOpenAiBlob(text, s) : await fetchElevenBlob(text, s); await saveCachedBlob(s, text, blob); return playBlob(blob, { provider: s.ttsProvider, voice: s.ttsVoice, model: s.ttsModel, format: s.ttsFormat, cached: false, textPreview: String(text).slice(0, 240) }); } } catch (err) { logDebug('tts.remote.error', { provider: s.ttsProvider, message: String(err), model: s.ttsModel, voice: s.ttsVoice }); } return speakBrowser(text); }
